name: Hello World

on:
  #workflow_dispatch:
  push:
  pull_request:

jobs:
  test_hello_world:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      with:
        robot_tests_dir: TESTE_HelloWorld
        
    #- name: test_hello_world
     # run: echo "Hello World"
